### ISSUE TITLE
 本地无法启动

### ISSUE THREAD

**Issue by Xinmiao-Zhuo** [iuap-design/designer#2]

**Comment by JSAL-** [comment]
It's OK now.
I solved it by separating the build command in package.json ,  which means to build it step by step.
```
"scripts": {
    "dev": "./node_modules/.bin/webpack-dev-server --progress",
    "server": "node server.js",
    "build": "rm -rf build && gulp && ./node_modules/.bin/webpack -p --progress --colors"
  },
```
change to 
```
"scripts": {
    "dev": "./node_modules/.bin/webpack-dev-server --progress",
    "server": "node server.js",
    "build": "rm -rf build"
  },
```
and than replace build command by "gulp" ,and " ./node_modules/.bin/webpack -p --progress --colors" at the last.
finally you input npm run dev, and open localhost:9000 , everything looks to be good~

poor English, never mind~

**Comment by JSAL-** [comment]
It's OK now.
I solved it by separating the build command in package.json ,  which means to build it step by step.
```
"scripts": {
    "dev": "./node_modules/.bin/webpack-dev-server --progress",
    "server": "node server.js",
    "build": "rm -rf build && gulp && ./node_modules/.bin/webpack -p --progress --colors"
  },
```
change to 
```
"scripts": {
    "dev": "./node_modules/.bin/webpack-dev-server --progress",
    "server": "node server.js",
    "build": "rm -rf build"
  },
```
and than replace build command by `gulp` ,and ` ./node_modules/.bin/webpack -p --progress --colors`at the last.
finally you input npm run dev, and open localhost:9000 , everything looks to be good~

poor English, never mind~
